"""
horary/horary_chart.py

KP Horary (Prashna) -- the querent picks a number from 1-249, and that
number identifies a specific point on the zodiac (via
data/horary_249_table.json, generated by
scripts/generate_horary_table.py from the same 243-row sub-lord table
core.sub_lord_engine uses, with the 6 sign-boundary-straddling divisions
split in two -- see that script's docstring for the full derivation).

This module has two jobs:
  1. Look up a horary number's sign/nakshatra/star-lord/sub-lord info
     (mirroring core.sub_lord_engine's shape, but keyed by horary number
     instead of a longitude).
  2. Cast the actual chart for the moment the horary question is being
     judged (real planetary positions and house cusps at that
     date/time/place, via core.ephemeris) and attach the horary number's
     lookup data plus its significators alongside it -- practiced KP
     horary judges the REAL chart cast for the moment of judgment, using
     the horary number's own sub lord as an additional point of
     evidence (much like an extra cuspal position), not as a
     replacement for the actual Ascendant.
"""

from __future__ import annotations

import bisect
import json
from datetime import datetime
from typing import Any

import config
from core.ephemeris import get_house_cusps, get_planet_positions
from core.significators import get_significators_for_chart

# Module-level cache, same lazy-load pattern as
# core.sub_lord_engine.load_sublord_table().
_HORARY_TABLE: list[dict] | None = None
_HORARY_BY_NUMBER: dict[int, dict] | None = None
_HORARY_START_DEGREES: list[float] | None = None


def load_horary_table() -> list[dict]:
    """
    Load the 249-row horary table from disk and cache it (plus a
    number-indexed lookup dict and a start-degree list for reverse
    longitude lookups), exactly once per process.

    Returns:
        The full list of 249 row dicts, sorted ascending by start_deg
        (equivalently, ascending by horary_number).
    """
    global _HORARY_TABLE, _HORARY_BY_NUMBER, _HORARY_START_DEGREES

    if _HORARY_TABLE is None:
        with open(config.HORARY_TABLE, "r", encoding="utf-8") as f:
            table = json.load(f)

        by_number = {row["horary_number"]: row for row in table}
        if set(by_number.keys()) != set(range(1, 250)):
            raise ValueError(
                "data/horary_249_table.json does not contain exactly "
                "horary numbers 1-249 -- check the table wasn't "
                "truncated or corrupted."
            )

        _HORARY_TABLE = table
        _HORARY_BY_NUMBER = by_number
        _HORARY_START_DEGREES = [row["start_deg"] for row in table]

    return _HORARY_TABLE


def validate_horary_number(number: int) -> None:
    """
    Check that `number` is a valid KP horary number (an integer in
    [config.HORARY_MIN_NUMBER, config.HORARY_MAX_NUMBER], i.e. 1-249).

    Args:
        number: The horary number to validate.

    Raises:
        ValueError: if `number` is out of range or not an integer.
    """
    if not isinstance(number, int) or isinstance(number, bool):
        raise ValueError(f"Horary number must be an int, got {number!r}")
    if not (config.HORARY_MIN_NUMBER <= number <= config.HORARY_MAX_NUMBER):
        raise ValueError(
            f"Horary number {number} out of range "
            f"[{config.HORARY_MIN_NUMBER}, {config.HORARY_MAX_NUMBER}]"
        )


def get_horary_number_info(number: int) -> dict:
    """
    Look up the sign, nakshatra, star lord, and sub lord for a given
    horary number -- the horary-table equivalent of
    core.sub_lord_engine.get_sublord_info(), but keyed by horary number
    instead of a raw longitude.

    Args:
        number: Horary number, 1-249.

    Returns:
        {
            "horary_number": 137,
            "sign": "Libra",
            "nakshatra": "Swati",
            "nakshatra_index": 15,
            "star_lord": "Rahu",
            "sub_lord": "Jupiter",
            "start_deg": 194.4444,
            "end_deg": 195.5556,
        }

    Raises:
        ValueError: if `number` is not a valid horary number (see
            validate_horary_number()).
    """
    validate_horary_number(number)
    load_horary_table()
    row = _HORARY_BY_NUMBER[number]

    return {
        "horary_number": number,
        "sign": row["sign"],
        "nakshatra": row["nakshatra"],
        "nakshatra_index": row["nakshatra_index"],
        "star_lord": row["star_lord"],
        "sub_lord": row["sub_lord"],
        "start_deg": row["start_deg"],
        "end_deg": row["end_deg"],
    }


def get_horary_number_for_longitude(longitude: float) -> int:
    """
    Reverse lookup: given a zodiacal longitude, find which of the 249
    horary numbers' ranges it falls into. Not needed for the standard
    "querent picks a number" horary workflow, but useful for
    diagnostics/testing (e.g. confirming the table has no gaps) or for
    any future feature that wants to express a longitude in horary-table
    terms.

    Args:
        longitude: Any float longitude in degrees (normalized with
            `% 360`).

    Returns:
        The horary number (1-249) whose range contains `longitude`.
    """
    load_horary_table()
    normalized = longitude % 360.0
    if normalized == 360.0:
        normalized = 0.0

    idx = bisect.bisect_right(_HORARY_START_DEGREES, normalized) - 1
    if idx < 0 or idx >= len(_HORARY_TABLE):
        raise ValueError(f"No horary table row found for longitude {normalized!r}")

    return _HORARY_TABLE[idx]["horary_number"]


def cast_horary_chart(
    horary_number: int,
    dt_local: datetime,
    tz_offset_hours: float,
    latitude: float,
    longitude: float,
) -> dict:
    """
    Cast a full horary chart: the real planetary positions and house
    cusps for the moment/place the question is being judged (exactly
    like a natal chart computation, via core.ephemeris), plus the
    querent's chosen horary number's lookup info and that number's sub
    lord's own house significations.

    Args:
        horary_number: The querent's chosen number, 1-249.
        dt_local: Local datetime of the moment of judgment (when the
            astrologer takes up the question -- KP horary convention is
            to cast for this moment, not the moment the question was
            first asked).
        tz_offset_hours: Timezone offset from UTC in hours.
        latitude: Latitude of the place of judgment, decimal degrees.
        longitude: Longitude of the place of judgment, decimal degrees.

    Returns:
        {
            "horary_point": { ... get_horary_number_info() shape ... },
            "chart_positions": core.ephemeris.ChartPositions,
            "house_cusps": { ... core.ephemeris.get_house_cusps() shape ... },
            "significators": { ... core.significators.compute_significators() shape ... },
        }
    """
    horary_point = get_horary_number_info(horary_number)

    chart_positions = get_planet_positions(
        dt_local=dt_local,
        tz_offset_hours=tz_offset_hours,
        latitude=latitude,
        longitude=longitude,
    )
    house_cusps = get_house_cusps(
        dt_local=dt_local,
        tz_offset_hours=tz_offset_hours,
        latitude=latitude,
        longitude=longitude,
    )
    significators = get_significators_for_chart(chart_positions, house_cusps)

    return {
        "horary_point": horary_point,
        "chart_positions": chart_positions,
        "house_cusps": house_cusps,
        "significators": significators,
    }
